#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

IFS=':'

while read -r usr pswd uid gid info home csh
do
	echo "The user $usr is part of the $gid gang, lives in $home and rides $csh. $uid's place is protected by the passcode $pswd, more info about the user here: $info"
done < /etc/passwd
