#!/usr/bin/env bash
# That script displays "Best School" 10 times but bad luck at 4 and good luck at 8
i=0
while ((i < 10))
do
	((i++))
	if (( i == 4 ))
	then
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
